### ISSUE TITLE
Implement Static Profile Page

### ISSUE THREAD

**Issue by chanteriam** [uchicago-capp-30320/ShoulderToShoulder#14]
## Implementation Details
The profile page will be composed of 3 pieces:
- [ ] The profile overview (issue #15)
- [ ] User preference survey (issue #16)
- [ ] User settings (issue #17)
