### ISSUE TITLE
Implement Static Webpages

### ISSUE THREAD

**Issue by chanteriam** [uchicago-capp-30320/ShoulderToShoulder#7]
A central PR for implementing the static (solely the html and css) webpages of the application. The pages to be implemented are:
- [x] Homepage (issue #8)
- [x] Login Page (issue #9)
- [x] Sign up Page (issue #10)
- [x] Profile page (issue #14)
    - [x] Profile overview (issue #15)
    - [x] Preferences survey (editable) (issue #16)
    - [x] Settings (editable) (issue #17)
- [x] Create events page (issue #13)
- [x] About us page (issue #12)
- [x] Contact us page (issue #11)

Our frontend UI will make use of the following color palette and associated HEX codes:
<img width="1359" alt="image" src="https://github.com/ehabich/ShoulderToShoulder/assets/68039600/8a9314f4-1ec2-455d-853e-5aea8e16cee8">

The figma prototype for the frontend UI can be found here: https://www.figma.com/file/PdDPO4LVkxrRyCxaoBfjNz/Civic-Tech-Project-Prototype-(Copy)?type=design&node-id=0-1&mode=design&t=9MQsC1I6HgbztRIi-0
